owner: constructions-incongrues
repo: club.jeancloude.status

sites:
  - name: allo.jeancloude.club
    url: https://allo.jeancloude.club
  - name: cartemembre.jeancloude.club
    url: https://cartemembre.jeancloude.club
  - name: grisbi.jeancloude.club
    url: https://grisbi.jeancloude.club
  - name: status.jeancloude.club
    url: https://status.jeancloude.club

assignees:
  - trivoallan

status-website:
  cname: status.jeancloude.club
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Club Jean-Cloude
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
