owner: constructions-incongrues
repo: club.jeancloude.status

sites:
  - name: Allo ?
    url: https://allo.jeancloude.club
  - name: Carte Membre
    url: https://cartemembre.jeancloude.club
  - name: Grisbi
    url: https://grisbi.jeancloude.club

status-website:
  cname: status.jeancloude.club
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Club Jean-Cloude
  introTitle: Le Cloude est dans l'hébergerie
  introMessage: <https://grisbi.jeancloude.club>
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
