owner: constructions-incongrues
repo: club.jeancloude.status

sites:
  - name: allo.jeancloude.club
    url: https://allo.jeancloude.club
  - name: cartemembre.jeancloude.club
    url: https://cartemembre.jeancloude.club
  - name: planque.jeancloude.club
    url: https://planque.jeancloude.club
  - name: status.jeancloude.club
    url: https://status.jeancloude.club
  - name: teloche.jeancloude.club
    url: https://teloche.jeancloude.club
  - name: vachercher.jeancloude.club
    url: https://vachercher.jeancloude.club

assignees:
  - trivoallan

status-website:
  cname: status.jeancloude.club
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Club Jean-Cloude
  introTitle: Comment allez-vous, Jean-Cloude ?

  navbar:
    - title: Constructions Incongrues
      href: https://status.constructions-incongrues.net
    - title: Pastis Hosting
      href: https://status.pastis-hosting.net
